<a href="https://colab.research.google.com/github/cokejunkie8191/data_scientist/blob/chapter_2/2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Scipyの基礎

In [0]:
# ライブラリのインポート
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
# 結果にグラフを表示
%matplotlib inline

# 小数第3位まで表示
%precision 3

# 乱数のシード=>これを実行しておくと、何回やっても同じ結果になる
random.seed(0)

# 線形代数用のライブラリ
import scipy.linalg as linalg

# 最適化計算(最小値)用の関数
from scipy.optimize import minimize_scalar

行列計算

In [9]:
# 行列式と逆行列の計算
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

# 行列式
print('行列式')
print(linalg.det(matrix))

# 逆行列
print('逆行列')
print(linalg.inv(matrix))

print(matrix.dot(linalg.inv(matrix)))

行列式
-4.0
逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)

print('固有値: ', eig_value)
print('固有ベクトル: ', eig_vector)

固有値:  [-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル:  [[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


ニュートン法

In [14]:
# 方程式の解を求める
# 関数の定義
def my_function(x):
  return (x ** 2 + x * 2 + 1)

# ニュートン法の読み込み
from scipy.optimize import newton

# 計算実行
print(newton(my_function, 0))

-0.9999999852953906


In [15]:
# 最小値を求める
print(minimize_scalar(my_function, method = 'Brent'))

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002


Practice

In [17]:
# 2-4
a = np.array([1, 2, 3, 1, 3, 2, 3, 1, 2]).reshape(3, 3)
print(linalg.det(a))

-12.0


In [19]:
# 2-5
eig_value, eig_vector = linalg.eig(a)
print('固有値: ', eig_value)
print('固有ベクトル: ', eig_vector)

固有値:  [ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル:  [[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]


In [22]:
# 2-6
def practice_function(x):
  return (x ** 3 + 2 * x + 1)

newton(practice_function, 0)

-0.453